# Generated by Django 3.2.4 on 2021-07-05 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rname', models.CharField(max_length=30)),
                ('nitems', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('rsimg', models.ImageField(default='bk.jpg', upload_to='RestaurentImages/')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itemlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iname', models.CharField(max_length=50)),
                ('Icategory', models.CharField(choices=[('select', 'Select Item Type'), ('veg', 'Veg'), ('non-veg', 'Non-Veg')], default='select', max_length=50)),
                ('Iprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Iavailability', models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available'), ('NA', 'Select Availability')], default='NA', max_length=50)),
                ('Iimage', models.ImageField(default='bk.jpg', upload_to='ItemImages/')),
                ('rsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApp.restaurents')),
            ],
        ),
    ]
