# Generated by Django 3.2.4 on 2021-06-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurents',
            name='rsimg',
            field=models.ImageField(default='bk.jpg', upload_to='RestaurentImages/'),
        ),
    ]
