# Generated by Django 3.2.4 on 2021-07-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0002_restaurents_rsimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iname', models.CharField(max_length=50)),
                ('Icategory', models.CharField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], default='select', max_length=50)),
                ('Iprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Iavailability', models.CharField(choices=[('Available', 'AV'), ('Not Available', 'NA')], default='None', max_length=50)),
                ('Iimage', models.ImageField(default='bk.jpg', upload_to='ItemImages/')),
            ],
        ),
    ]
