# Generated by Django 3.2.4 on 2021-07-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0003_itemlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='Iavailability',
            field=models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available')], default='None', max_length=50),
        ),
    ]
