# Generated by Django 3.2.4 on 2021-07-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0004_alter_itemlist_iavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='Iavailability',
            field=models.CharField(choices=[('AV', 'Available'), ('NA', 'Not Available'), ('NA', 'Select Availability')], default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='Icategory',
            field=models.CharField(choices=[('select', 'Select Item Type'), ('veg', 'Veg'), ('non-veg', 'Non-Veg')], default='select', max_length=50),
        ),
    ]
